In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
l1 = [1,2,3,4,"namirah", 34.25, True]

In [11]:
a1 = np.array(l1)

In [12]:
a2 = np.array([[1,2,3,], [4,5,6,]])

In [13]:
a3 = np.array([[[1,2,3,], [4,5,6,], [7,8,9]]])

In [14]:
a1

array(['1', '2', '3', '4', 'namirah', '34.25', 'True'], dtype='<U32')

In [15]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [18]:
a1.ndim

1

In [19]:
a2.ndim

2

In [21]:
a3.ndim

3

In [22]:
a1.size

7

In [23]:
a2.size

6

In [24]:
a3.size

9

In [25]:
a1.shape

(7,)

In [26]:
a2.shape

(2, 3)

In [27]:
a3.shape

(1, 3, 3)

In [28]:
a1

array(['1', '2', '3', '4', 'namirah', '34.25', 'True'], dtype='<U32')

In [29]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
np.random.randint(2,50 , (3,4))

array([[16, 20, 25, 26],
       [10, 12,  2, 15],
       [37, 18, 33, 38]])

In [37]:
np.random.randint(2,50 , (2,3,4))

array([[[43, 46,  8, 25],
        [23, 36, 12, 37],
        [49, 34, 12, 12]],

       [[ 5,  9, 21, 32],
        [33,  9, 11, 45],
        [38, 14, 29, 17]]])

In [41]:
np.random.rand(5,3)

array([[0.20807126, 0.95979699, 0.23335921],
       [0.93691393, 0.12161391, 0.08700056],
       [0.02991846, 0.50085061, 0.75516838],
       [0.54745222, 0.16150157, 0.51491852],
       [0.82999268, 0.98672644, 0.86562434]])

In [42]:
a4 = np.random.randn(4,4)

In [43]:
a4

array([[-0.0986353 ,  0.30668644,  0.70021366,  0.47634052],
       [-0.26547712,  1.0292165 , -0.07794031,  1.51401771],
       [-0.68084908, -1.11990757, -0.03008262,  0.76201867],
       [ 1.82751052, -0.16359397,  0.51413361, -0.6988274 ]])

In [46]:
a4.reshape(2,8)

array([[-0.0986353 ,  0.30668644,  0.70021366,  0.47634052, -0.26547712,
         1.0292165 , -0.07794031,  1.51401771],
       [-0.68084908, -1.11990757, -0.03008262,  0.76201867,  1.82751052,
        -0.16359397,  0.51413361, -0.6988274 ]])

In [47]:
a4.reshape(8,2)

array([[-0.0986353 ,  0.30668644],
       [ 0.70021366,  0.47634052],
       [-0.26547712,  1.0292165 ],
       [-0.07794031,  1.51401771],
       [-0.68084908, -1.11990757],
       [-0.03008262,  0.76201867],
       [ 1.82751052, -0.16359397],
       [ 0.51413361, -0.6988274 ]])

In [48]:
a4.reshape(16,1)

array([[-0.0986353 ],
       [ 0.30668644],
       [ 0.70021366],
       [ 0.47634052],
       [-0.26547712],
       [ 1.0292165 ],
       [-0.07794031],
       [ 1.51401771],
       [-0.68084908],
       [-1.11990757],
       [-0.03008262],
       [ 0.76201867],
       [ 1.82751052],
       [-0.16359397],
       [ 0.51413361],
       [-0.6988274 ]])

In [49]:
a4.reshape(1,16)

array([[-0.0986353 ,  0.30668644,  0.70021366,  0.47634052, -0.26547712,
         1.0292165 , -0.07794031,  1.51401771, -0.68084908, -1.11990757,
        -0.03008262,  0.76201867,  1.82751052, -0.16359397,  0.51413361,
        -0.6988274 ]])

In [50]:
a4.reshape(2,-1)

array([[-0.0986353 ,  0.30668644,  0.70021366,  0.47634052, -0.26547712,
         1.0292165 , -0.07794031,  1.51401771],
       [-0.68084908, -1.11990757, -0.03008262,  0.76201867,  1.82751052,
        -0.16359397,  0.51413361, -0.6988274 ]])

In [51]:
a4.reshape(2,2,4)

array([[[-0.0986353 ,  0.30668644,  0.70021366,  0.47634052],
        [-0.26547712,  1.0292165 , -0.07794031,  1.51401771]],

       [[-0.68084908, -1.11990757, -0.03008262,  0.76201867],
        [ 1.82751052, -0.16359397,  0.51413361, -0.6988274 ]]])

In [52]:
a1

array(['1', '2', '3', '4', 'namirah', '34.25', 'True'], dtype='<U32')

In [53]:
a1[0]

'1'

In [54]:
a1[2:6]

array(['3', '4', 'namirah', '34.25'], dtype='<U32')

In [55]:
a1[2:6:2]

array(['3', 'namirah'], dtype='<U32')

In [56]:
a1[::-1]

array(['True', '34.25', 'namirah', '4', '3', '2', '1'], dtype='<U32')

In [57]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [58]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a2[0]

array([1, 2, 3])

In [60]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [61]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [64]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [66]:
a5 = np.random.randint(2,90, (6,5) )

In [67]:
a5

array([[21, 39, 88, 65, 56],
       [40, 77, 82, 49, 43],
       [73, 79, 55, 43, 18],
       [49, 50, 48, 26, 29],
       [35,  9, 65, 35, 65],
       [35, 70,  5,  4, 46]])

In [68]:
a5[a5>40]

array([88, 65, 56, 77, 82, 49, 43, 73, 79, 55, 43, 49, 50, 48, 65, 65, 70,
       46])

In [69]:
a5

array([[21, 39, 88, 65, 56],
       [40, 77, 82, 49, 43],
       [73, 79, 55, 43, 18],
       [49, 50, 48, 26, 29],
       [35,  9, 65, 35, 65],
       [35, 70,  5,  4, 46]])

In [70]:
a5[0,1] = 100

In [71]:
a5

array([[ 21, 100,  88,  65,  56],
       [ 40,  77,  82,  49,  43],
       [ 73,  79,  55,  43,  18],
       [ 49,  50,  48,  26,  29],
       [ 35,   9,  65,  35,  65],
       [ 35,  70,   5,   4,  46]])

In [77]:
a6 = np.random.randint(0,3, (3,3))

In [78]:
a7 = np.random.randint(0,3, (3,3))

In [79]:
a6

array([[0, 0, 0],
       [0, 0, 2],
       [0, 1, 1]])

In [80]:
a7

array([[1, 2, 2],
       [1, 1, 0],
       [2, 1, 0]])

In [81]:
a6*a7

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [82]:
a6@a7

array([[0, 0, 0],
       [4, 2, 0],
       [3, 2, 0]])

In [83]:
a6

array([[0, 0, 0],
       [0, 0, 2],
       [0, 1, 1]])

In [84]:
a6+100

array([[100, 100, 100],
       [100, 100, 102],
       [100, 101, 101]])

In [85]:
a6*2

array([[0, 0, 0],
       [0, 0, 4],
       [0, 2, 2]])

In [86]:
a6/0

C:\Users\bewna\AppData\Local\Temp/ipykernel_11176/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\bewna\AppData\Local\Temp/ipykernel_11176/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, nan, nan],
       [nan, nan, inf],
       [nan, inf, inf]])

In [87]:
a6

array([[0, 0, 0],
       [0, 0, 2],
       [0, 1, 1]])

In [88]:
a6**3

array([[0, 0, 0],
       [0, 0, 8],
       [0, 1, 1]], dtype=int32)

In [89]:
a8 = np.zeros((4,4))

In [90]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
a9 = np.ones((4,5))

In [93]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [95]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [96]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [102]:
np.array([[1,2,3,4]]).T +a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [103]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [104]:
a6

array([[0, 0, 0],
       [0, 0, 2],
       [0, 1, 1]])

In [105]:
a6.T

array([[0, 0, 0],
       [0, 0, 1],
       [0, 2, 1]])

In [106]:
a5

array([[ 21, 100,  88,  65,  56],
       [ 40,  77,  82,  49,  43],
       [ 73,  79,  55,  43,  18],
       [ 49,  50,  48,  26,  29],
       [ 35,   9,  65,  35,  65],
       [ 35,  70,   5,   4,  46]])

In [107]:
np.sqrt(a5)

array([[ 4.58257569, 10.        ,  9.38083152,  8.06225775,  7.48331477],
       [ 6.32455532,  8.77496439,  9.05538514,  7.        ,  6.55743852],
       [ 8.54400375,  8.88819442,  7.41619849,  6.55743852,  4.24264069],
       [ 7.        ,  7.07106781,  6.92820323,  5.09901951,  5.38516481],
       [ 5.91607978,  3.        ,  8.06225775,  5.91607978,  8.06225775],
       [ 5.91607978,  8.36660027,  2.23606798,  2.        ,  6.78232998]])

In [108]:
np.exp(a5)

array([[1.31881573e+09, 2.68811714e+43, 1.65163625e+38, 1.69488924e+28,
        2.09165950e+24],
       [2.35385267e+17, 2.75851345e+33, 4.09399696e+35, 1.90734657e+21,
        4.72783947e+18],
       [5.05239363e+31, 2.03828107e+34, 7.69478527e+23, 4.72783947e+18,
        6.56599691e+07],
       [1.90734657e+21, 5.18470553e+21, 7.01673591e+20, 1.95729609e+11,
        3.93133430e+12],
       [1.58601345e+15, 8.10308393e+03, 1.69488924e+28, 1.58601345e+15,
        1.69488924e+28],
       [1.58601345e+15, 2.51543867e+30, 1.48413159e+02, 5.45981500e+01,
        9.49611942e+19]])

In [109]:
np.log10(a5)

array([[1.32221929, 2.        , 1.94448267, 1.81291336, 1.74818803],
       [1.60205999, 1.88649073, 1.91381385, 1.69019608, 1.63346846],
       [1.86332286, 1.89762709, 1.74036269, 1.63346846, 1.25527251],
       [1.69019608, 1.69897   , 1.68124124, 1.41497335, 1.462398  ],
       [1.54406804, 0.95424251, 1.81291336, 1.54406804, 1.81291336],
       [1.54406804, 1.84509804, 0.69897   , 0.60205999, 1.66275783]])

In [111]:
list (range(0,10, 2))

[0, 2, 4, 6, 8]

In [115]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [117]:
np.linspace(2,3, num=50, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [118]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [119]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [132]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns



Matplotlib is building the font cache; this may take a moment.


In [125]:
!pip install cufflinks

In [126]:
import cufflinks as cf

In [127]:
cf.go_offline()

In [130]:
import pandas as pd

In [143]:
df = pd.DataFrame(np.random.randn(100,3), columns=['A','B','C'])

In [144]:
df

A         B         C
0   0.225363  0.501125  1.438150
1   1.616046 -0.023446 -0.121357
2  -0.675440  0.733075  0.249314
3  -0.771454 -1.579748 -0.868755
4   0.314652  1.467178  0.314187
..       ...       ...       ...
95  0.229945  0.754838 -0.721490
96 -0.986539  0.915841 -1.697283
97  0.018326  1.458221  0.685435
98  0.198221 -0.123742  0.818613
99 -1.244681  0.137889 -1.250448

[100 rows x 3 columns]

In [145]:
df.iplot()

In [149]:
df1 = pd.DataFrame(np.random.randint(3,100, (100,1)))

In [150]:
df1

0
0   22
1   22
2   24
3   97
4   56
..  ..
95  63
96  69
97  67
98  70
99  98

[100 rows x 1 columns]

In [148]:
df1.iplot()

In [151]:
df1

0
0   22
1   22
2   24
3   97
4   56
..  ..
95  63
96  69
97  67
98  70
99  98

[100 rows x 1 columns]

In [152]:
df

A         B         C
0   0.225363  0.501125  1.438150
1   1.616046 -0.023446 -0.121357
2  -0.675440  0.733075  0.249314
3  -0.771454 -1.579748 -0.868755
4   0.314652  1.467178  0.314187
..       ...       ...       ...
95  0.229945  0.754838 -0.721490
96 -0.986539  0.915841 -1.697283
97  0.018326  1.458221  0.685435
98  0.198221 -0.123742  0.818613
99 -1.244681  0.137889 -1.250448

[100 rows x 3 columns]

In [154]:
df.iplot(x = 'A', y = 'B', mode = 'markers')

In [156]:
df2 =sns.load_dataset('titanic')

In [157]:
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [158]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [159]:
df2.iplot(x = 'age', y = 'fare', mode = 'markers')

In [160]:
df2.iplot(x = 'age', y = 'pclass', mode = 'markers')

In [161]:
df2.iplot(x = 'fare', y = 'pclass', mode = 'markers')

In [162]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [163]:
df2.iplot(kind = 'bar', x = 'sex', y = 'survived')